"use client";

import { BadgeCheck, Check, ChevronRight, CircleDollarSign, Copy, Eye, FileDown, Filter, Percent, Save, Settings, ShieldCheck, UserCheck, UsersRound, X, XCircle } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

type WorkItem = { id:string; module:string; record_type:string; title:string; customer_name:string; owner:string; team:string; status:string; amount_cents:number; description:string; version:number; updated_at:string; created_at:string };
type Catalog = { id:string; catalog:string; name:string; description:string; active:boolean };
type Employee = { id:string; displayName:string; email:string; departmentName:string; departmentNames:string[]; photoDataUrl?:string; active:boolean };
type User = { email:string; displayName:string; role:string; department:string; photoDataUrl:string };
type OperationResult = { id?:string } | false;
type Scope = "commercial" | "cs" | "lia";
type Decision = "pending" | "approved" | "rejected";
type Rule = { kind:"commissionRule"; scope:Scope; employeeId:string; employeeName:string; product:string; type:"percentage"|"fixed"; value:number };
type CommissionRecord = { kind:"commissionRecord"; sourceKey:string; sourceId:string; scope:Scope; competence:string; employeeId:string; employeeName:string; employeePhoto:string; customerName:string; product:string; saleValueCents:number; score:number|null; commissionCents:number; ruleLabel:string; decision:Decision; reason:string; decidedBy:string; decidedAt:string; viewedAt:string; agreedAt:string };
type Row = Omit<CommissionRecord,"kind"|"commissionCents"|"ruleLabel"|"decision"|"reason"|"decidedBy"|"decidedAt"|"viewedAt"|"agreedAt"> & { record?:WorkItem; recordDetail?:CommissionRecord; proposedCents:number; ruleLabel:string; ruleFound:boolean };

const money=(cents:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100);
const date=(value?:string)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";
const monthLabel=(value:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(`${value}-02T12:00:00`));
const previousMonth=()=>{const value=new Date();value.setMonth(value.getMonth()-1);return value.toISOString().slice(0,7)};
const safe=<T,>(value:string):T|null=>{try{return JSON.parse(value) as T}catch{return null}};
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]!));
const avatar=(name:string,photo?:string)=><span className={`commission-avatar ${photo?"has-photo":""}`} style={photo?{backgroundImage:`url("${photo}")`}:undefined}>{!photo&&name.split(" ").map(part=>part[0]).slice(0,2).join("").toUpperCase()}</span>;
const scopeLabel=(scope:Scope)=>scope==="commercial"?"Comercial":scope==="lia"?"LIA":"Sucesso do Cliente";

function parseRule(value:string){const parsed=safe<Partial<Rule>>(value);return parsed?.kind==="commissionRule"&&(["commercial","cs","lia"] as string[]).includes(String(parsed.scope))?parsed as Rule:null}
function parseRecord(value:string){const parsed=safe<Partial<CommissionRecord>>(value);return parsed?.kind==="commissionRecord"?{...parsed,score:typeof parsed.score==="number"?parsed.score:null,commissionCents:Number(parsed.commissionCents||0),decision:parsed.decision||"pending",reason:parsed.reason||"",decidedBy:parsed.decidedBy||"",decidedAt:parsed.decidedAt||"",viewedAt:parsed.viewedAt||"",agreedAt:parsed.agreedAt||""} as CommissionRecord:null}
function health(detail:Record<string,unknown>){const base=Array.isArray(detail.featuresBase)?detail.featuresBase.flatMap(value=>String(value).split(",")).map(value=>normalize(value.trim())).filter(Boolean):[];const active=Array.isArray(detail.featuresActive)?detail.featuresActive.flatMap(value=>String(value).split(",")).map(value=>normalize(value.trim())).filter(Boolean):[];if(!base.length)return 0;return Math.round(Math.max(0,Math.min(1,base.filter(feature=>active.some(value=>value.includes(feature))).length/base.length))*100)}
function commercialProducts(detail:Record<string,unknown>){const products=Array.isArray(detail.products)?detail.products as Array<Record<string,unknown>>:[];return products.map(product=>({name:String(product.product||product.name||"Produto não informado"),quantity:Math.max(1,Number(product.quantity||1)),unit:Number(product.unitValue??product.value??0)}))}

export default function CommissionsModule({items,catalogs,employees,currentUser,busy,canApprove,canManage,operate}:{items:WorkItem[];catalogs:Catalog[];employees:Employee[];currentUser:User;busy:boolean;canApprove:boolean;canManage:boolean;operate:(payload:Record<string,unknown>,success:string)=>Promise<OperationResult>}){
  const [scope,setScope]=useState<Scope>("commercial");const [competence,setCompetence]=useState(previousMonth());const [employeeFilter,setEmployeeFilter]=useState("all");const [statusFilter,setStatusFilter]=useState("all");const [settings,setSettings]=useState(false);const [decision,setDecision]=useState<{row:Row;decision:"approved"|"rejected"}|null>(null);const [notice,setNotice]=useState("");const [requestedCommission]=useState(()=>typeof window==="undefined"?null:new URLSearchParams(window.location.search).get("commission"));
  const activeEmployees=employees.filter(employee=>employee.active);const rules=catalogs.map(entry=>({entry,rule:parseRule(entry.description)})).filter((entry):entry is {entry:Catalog;rule:Rule}=>entry.entry.active&&entry.entry.catalog==="commissionRule"&&Boolean(entry.rule));
  const records=items.filter(item=>item.module==="commissions").map(item=>({item,detail:parseRecord(item.description)})).filter((entry):entry is {item:WorkItem;detail:CommissionRecord}=>Boolean(entry.detail));
  useEffect(()=>{if(!requestedCommission)return;const linked=records.find(entry=>entry.item.id===requestedCommission||entry.detail.sourceKey===requestedCommission);if(!linked)return;setScope(linked.detail.scope);setCompetence(linked.detail.competence);setEmployeeFilter(linked.detail.employeeName)},[requestedCommission,items.length]);
  const sourceRows=useMemo(()=>{
    const rows:Array<Omit<Row,"proposedCents"|"ruleLabel"|"ruleFound"|"record"|"recordDetail">>=[];
    if(scope==="commercial")items.filter(item=>item.module==="commercial").forEach(item=>{const detail=safe<Record<string,unknown>>(item.description)||{};const direct=detail.kind==="directSale";const won=direct||/ganho|fechad|conclu|vendid/i.test(`${item.status} ${String(detail.stage||"")}`);if(!won)return;const entryMonth=String(direct?detail.saleDate||item.updated_at:item.updated_at).slice(0,7);if(entryMonth!==competence)return;const seller=String(detail.seller||item.owner||"Não atribuído");const employee=activeEmployees.find(entry=>normalize(entry.displayName)===normalize(seller));const products=commercialProducts(detail);(products.length?products:[{name:item.record_type,quantity:1,unit:item.amount_cents/100}]).forEach((product,index)=>rows.push({sourceKey:`${item.id}:${index}`,sourceId:item.id,scope:"commercial",competence:entryMonth,employeeId:employee?.id||"",employeeName:seller,employeePhoto:employee?.photoDataUrl||"",customerName:String(detail.name||detail.customer||item.customer_name||item.title),product:product.name,saleValueCents:Math.round(product.unit*product.quantity*100)||item.amount_cents,score:null}))});
    else items.filter(item=>item.module===scope).forEach(item=>{const detail=safe<Record<string,unknown>>(item.description)||{};if(scope==="cs"&&detail.kind!=="csJourney")return;if(scope==="lia"&&detail.kind!=="liaJourney")return;const entryMonth=item.created_at.slice(0,7);if(entryMonth!==competence)return;const employee=activeEmployees.find(entry=>normalize(entry.displayName)===normalize(item.owner));const source=items.find(entry=>entry.id===String(detail.sourceLeadId||detail.sourceId||""));const sourceDetail=source?safe<Record<string,unknown>>(source.description)||{}:{};const products=commercialProducts(sourceDetail);rows.push({sourceKey:item.id,sourceId:item.id,scope,competence:entryMonth,employeeId:employee?.id||"",employeeName:item.owner||"Não atribuído",employeePhoto:employee?.photoDataUrl||"",customerName:item.customer_name||item.title,product:products.map(product=>product.name).join(", ")||item.record_type,saleValueCents:item.amount_cents||source?.amount_cents||0,score:health(detail)})});
    return rows;
  },[scope,competence,items,activeEmployees]);
  const consolidatedRows=[...sourceRows,...records.filter(entry=>entry.detail.scope===scope&&entry.detail.competence===competence&&!sourceRows.some(row=>row.sourceKey===entry.detail.sourceKey)).map(({detail})=>({sourceKey:detail.sourceKey,sourceId:detail.sourceId,scope:detail.scope,competence:detail.competence,employeeId:detail.employeeId,employeeName:detail.employeeName,employeePhoto:detail.employeePhoto,customerName:detail.customerName,product:detail.product,saleValueCents:detail.saleValueCents,score:detail.score}))];
  const rows:Row[]=consolidatedRows.map(row=>{const record=records.find(entry=>entry.detail.sourceKey===row.sourceKey&&entry.detail.scope===scope)?.item;const recordDetail=record?parseRecord(record.description)||undefined:undefined;const rule=rules.find(entry=>entry.rule.scope===scope&&normalize(entry.rule.employeeName)===normalize(row.employeeName)&&(scope!=="commercial"||entry.rule.product==="*"||normalize(entry.rule.product)===normalize(row.product)))?.rule;const proposedCents=rule?(rule.type==="percentage"?Math.round(row.saleValueCents*rule.value/100):Math.round(rule.value*100)):recordDetail?.commissionCents||0;return {...row,record,recordDetail,proposedCents,ruleLabel:rule?rule.type==="percentage"?`${rule.value}% sobre ${money(row.saleValueCents)}`:`${money(Math.round(rule.value*100))} fixos`:recordDetail?.ruleLabel||"Regra não configurada",ruleFound:Boolean(rule||recordDetail)}});
  const visible=rows.filter(row=>(employeeFilter==="all"||row.employeeName===employeeFilter)&&(statusFilter==="all"||(row.recordDetail?.decision||"pending")===statusFilter)&&((canApprove||canManage)||normalize(row.employeeName)===normalize(currentUser.displayName)));
  const approved=visible.filter(row=>row.recordDetail?.decision==="approved");const approvedTotal=approved.reduce((sum,row)=>sum+(row.recordDetail?.commissionCents||0),0);const proposedTotal=visible.reduce((sum,row)=>sum+row.proposedCents,0);
  async function decide(row:Row,next:"approved"|"rejected",reason:string){const detail:CommissionRecord={kind:"commissionRecord",sourceKey:row.sourceKey,sourceId:row.sourceId,scope,competence:row.competence,employeeId:row.employeeId,employeeName:row.employeeName,employeePhoto:row.employeePhoto,customerName:row.customerName,product:row.product,saleValueCents:row.saleValueCents,score:row.score,commissionCents:next==="approved"?row.proposedCents:0,ruleLabel:row.ruleLabel,decision:next,reason,decidedBy:currentUser.displayName,decidedAt:new Date().toISOString(),viewedAt:row.recordDetail?.viewedAt||"",agreedAt:row.recordDetail?.agreedAt||""};const payload=row.record?{action:"updateWorkItem",id:row.record.id,title:`${row.employeeName} · ${row.customerName}`,owner:row.employeeName,amountCents:detail.commissionCents,version:row.record.version,description:JSON.stringify(detail)}:{action:"createWorkItem",module:"commissions",recordType:`Comissão ${scopeLabel(scope)}`,title:`${row.employeeName} · ${row.customerName}`,customerName:row.customerName,owner:row.employeeName,team:scopeLabel(scope),status:next==="approved"?"Aprovada":"Reprovada",priority:"P3",amountCents:detail.commissionCents,description:JSON.stringify(detail)};const result=await operate(payload,`Comissão ${next==="approved"?"aprovada":"reprovada"} e registrada.`);if(result)setDecision(null)}
  async function acknowledge(row:Row){if(!row.record||!row.recordDetail)return;const detail={...row.recordDetail,viewedAt:row.recordDetail.viewedAt||new Date().toISOString(),agreedAt:new Date().toISOString()};await operate({action:"updateWorkItem",id:row.record.id,title:row.record.title,owner:row.record.owner,amountCents:row.record.amount_cents,version:row.record.version,description:JSON.stringify(detail)},"Ciência e concordância registradas.")}
  const copyLink=async(row:Row)=>{const id=row.record?.id||row.sourceKey;await navigator.clipboard.writeText(`${window.location.origin}/?mod=commissions&commission=${encodeURIComponent(id)}`);setNotice("Link copiado para envio ao colaborador.");window.setTimeout(()=>setNotice(""),2500)};
  const report=()=>{const finalRows=visible.filter(row=>["approved","rejected"].includes(row.recordDetail?.decision||""));const popup=window.open("","_blank","noopener,noreferrer");if(!popup)return;const groups=[...new Set(finalRows.map(row=>row.employeeName))];popup.document.write(`<!doctype html><html><head><title>Comissões Dontus · ${competence}</title><style>body{font:12px Arial;color:#122033;padding:32px}header{border-bottom:3px solid #087fea;padding-bottom:16px}h1{margin:0;font-size:26px}.employee{page-break-inside:avoid;margin:26px 0}.person{display:flex;align-items:center;gap:12px}.person img,.initial{width:52px;height:52px;border-radius:14px;object-fit:cover;background:#e5f2ff;display:grid;place-items:center;font-weight:bold}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{border:1px solid #dce5ef;padding:8px;text-align:left}th{background:#edf6ff}.ok{color:#087a4d}.no{color:#b4233b}.total{text-align:right;font-size:15px;font-weight:bold;margin-top:10px}</style></head><body><header><h1>Dontus · Relatório de Comissões</h1><p>${escapeHtml(scope==="commercial"?"Comercial":"Sucesso do Cliente")} · ${escapeHtml(monthLabel(competence))} · emitido em ${escapeHtml(date(new Date().toISOString()))}</p></header>${groups.map(name=>{const group=finalRows.filter(row=>row.employeeName===name);const photo=group[0]?.employeePhoto;return `<section class="employee"><div class="person">${photo?`<img src="${escapeHtml(photo)}">`:`<div class="initial">${escapeHtml(name.slice(0,2).toUpperCase())}</div>`}<div><h2>${escapeHtml(name)}</h2><p>${group.length} lançamento(s)</p></div></div><table><thead><tr><th>Cliente</th><th>Produto</th><th>Venda</th><th>Score</th><th>Decisão</th><th>Comissão</th><th>Motivo</th></tr></thead><tbody>${group.map(row=>`<tr><td>${escapeHtml(row.customerName)}</td><td>${escapeHtml(row.product)}</td><td>${money(row.saleValueCents)}</td><td>${row.score===null?"—":`${row.score}%`}</td><td class="${row.recordDetail?.decision==="approved"?"ok":"no"}">${row.recordDetail?.decision==="approved"?"Aprovada":"Reprovada"}</td><td>${money(row.recordDetail?.commissionCents||0)}</td><td>${escapeHtml(row.recordDetail?.reason||"")}</td></tr>`).join("")}</tbody></table><p class="total">Total aprovado: ${money(group.reduce((sum,row)=>sum+(row.recordDetail?.commissionCents||0),0))}</p></section>`}).join("")}<script>window.print()<\/script></body></html>`);popup.document.close()};
  if(settings)return <CommissionSettings catalogs={catalogs} employees={activeEmployees} busy={busy} operate={operate} onBack={()=>setSettings(false)}/>;
  return <section className="commissions-module task-visual-standard"><header className="module-page-header"><div className="module-page-title"><span className="module-page-title-icon"><CircleDollarSign size={21}/></span><span className="module-page-copy"><span className="eyebrow">GESTÃO · REMUNERAÇÃO VARIÁVEL</span><h1>Comissões</h1><p>Conferência mensal, aprovação justificada e ciência do colaborador.</p></span></div><div className="module-page-actions">{notice&&<span className="commission-notice"><Check size={14}/>{notice}</span>}{canManage&&<button className="icon-button" onClick={()=>setSettings(true)} title="Configurar comissões"><Settings size={18}/></button>}<button className="secondary-button" onClick={report} disabled={!visible.some(row=>["approved","rejected"].includes(row.recordDetail?.decision||""))}><FileDown size={16}/>Gerar PDF</button></div></header>
    <nav className="commission-tabs"><button className={scope==="commercial"?"active":""} onClick={()=>setScope("commercial")}><CircleDollarSign/>Comercial</button><button className={scope==="cs"?"active":""} onClick={()=>setScope("cs")}><ShieldCheck/>Sucesso do Cliente</button><button className={scope==="lia"?"active":""} onClick={()=>setScope("lia")}><Percent/>Comissão LIA</button></nav>
    <section className="commission-summary"><article><span>Competência</span><strong>{monthLabel(competence)}</strong><small>{visible.length} lançamento(s)</small></article><article><span>Valor analisado</span><strong>{money(visible.reduce((sum,row)=>sum+row.saleValueCents,0))}</strong><small>base de cálculo</small></article><article><span>Comissão prevista</span><strong>{money(proposedTotal)}</strong><small>conforme regras</small></article><article className="positive"><span>Total aprovado</span><strong>{money(approvedTotal)}</strong><small>{approved.length} aprovação(ões)</small></article></section>
    <section className="commission-filters panel"><label><Filter size={15}/><input type="month" value={competence} onChange={event=>setCompetence(event.target.value)}/></label><select value={employeeFilter} onChange={event=>setEmployeeFilter(event.target.value)}><option value="all">Todos os colaboradores</option>{[...new Set(rows.map(row=>row.employeeName))].map(name=><option key={name}>{name}</option>)}</select><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="all">Todas as decisões</option><option value="pending">Pendentes</option><option value="approved">Aprovadas</option><option value="rejected">Reprovadas</option></select><strong>{visible.length} resultado(s)</strong></section>
    <section className="commission-table"><div className="commission-row head"><span>Cliente / produto</span><span>Colaborador</span><span>{scope==="commercial"?"Venda":"Score"}</span><span>Regra e cálculo</span><span>Decisão</span><span>Ações</span></div>{visible.length===0?<div className="commission-empty"><CircleDollarSign/><h2>Nenhum lançamento nesta competência</h2><p>As vendas e os clientes encaminhados aparecerão automaticamente aqui.</p></div>:visible.map(row=>{const detail=row.recordDetail;return <article className="commission-row" key={row.sourceKey}><span><strong>{row.customerName}</strong><small>{row.product} · {money(row.saleValueCents)}</small></span><span className="commission-person" data-collaborator-name={row.employeeName}>{avatar(row.employeeName,row.employeePhoto)}<span><strong>{row.employeeName}</strong><small>{scope==="commercial"?"Comercial":"Sucesso do Cliente"}</small></span></span><span><strong>{scope==="commercial"?money(row.saleValueCents):row.score===null?"LIA":`${row.score}%`}</strong><small>{scope==="commercial"?row.competence:"score de utilização"}</small></span><span><strong>{row.ruleFound?money(row.proposedCents):"Pendente"}</strong><small className={!row.ruleFound?"warning":""}>{row.ruleLabel}</small></span><span><b className={`commission-status ${detail?.decision||"pending"}`}>{detail?.decision==="approved"?"Aprovada":detail?.decision==="rejected"?"Reprovada":"Pendente"}</b>{detail?.reason&&<small title={detail.reason}>{detail.reason}</small>}{detail?.agreedAt&&<small className="agreed"><UserCheck size={12}/>Visto e de acordo</small>}</span><span className="commission-actions">{canApprove&&<><button disabled={!row.ruleFound||busy} title="Aprovar" onClick={()=>setDecision({row,decision:"approved"})}><BadgeCheck/></button><button disabled={busy} className="danger" title="Reprovar" onClick={()=>setDecision({row,decision:"rejected"})}><XCircle/></button></>} {detail&&<button title="Copiar link" onClick={()=>void copyLink(row)}><Copy/></button>}{detail?.decision==="approved"&&normalize(row.employeeName)===normalize(currentUser.displayName)&&!detail.agreedAt&&<button className="agree" onClick={()=>void acknowledge(row)}><Eye/>Li e concordo</button>}</span></article>})}</section>
    {decision&&<DecisionModal row={decision.row} decision={decision.decision} busy={busy} onClose={()=>setDecision(null)} onSubmit={reason=>decide(decision.row,decision.decision,reason)}/>}</section>;
}

function DecisionModal({row,decision,busy,onClose,onSubmit}:{row:Row;decision:"approved"|"rejected";busy:boolean;onClose:()=>void;onSubmit:(reason:string)=>Promise<void>}){const [reason,setReason]=useState("");return <div className="modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><section className="modal commission-decision-modal"><header className="modal-head"><div><span className="eyebrow">DECISÃO DE COMISSÃO</span><h2>{decision==="approved"?"Aprovar lançamento":"Reprovar lançamento"}</h2><p>{row.customerName} · {row.employeeName}</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="commission-decision-preview"><span><small>Produto</small><strong>{row.product}</strong></span><span><small>Venda</small><strong>{money(row.saleValueCents)}</strong></span><span><small>Comissão</small><strong>{decision==="approved"?money(row.proposedCents):money(0)}</strong></span></div><label>Motivo da decisão *<textarea rows={4} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Registre os critérios usados nesta decisão."/></label><footer><button onClick={onClose}>Cancelar</button><button className={decision==="approved"?"primary-button":"danger-button"} disabled={busy||reason.trim().length<3} onClick={()=>void onSubmit(reason.trim())}>{decision==="approved"?<BadgeCheck/>:<XCircle/>}{decision==="approved"?"Confirmar aprovação":"Confirmar reprovação"}</button></footer></section></div>}

function CommissionSettings({catalogs,employees,busy,operate,onBack}:{catalogs:Catalog[];employees:Employee[];busy:boolean;operate:(payload:Record<string,unknown>,success:string)=>Promise<OperationResult>;onBack:()=>void}){
  const [scope,setScope]=useState<Scope>("commercial");
  const [employeeId,setEmployeeId]=useState("");
  const employee=employees.find(entry=>entry.id===employeeId);
  const products=catalogs.filter(entry=>entry.active&&entry.catalog==="commercialProduct");
  const rules=catalogs.map(entry=>({entry,rule:parseRule(entry.description)})).filter((entry):entry is {entry:Catalog;rule:Rule}=>entry.entry.catalog==="commissionRule"&&Boolean(entry.rule));
  const save=(event:FormEvent<HTMLFormElement>,product:string,existing?:{entry:Catalog;rule:Rule})=>{event.preventDefault();if(!employee)return;const form=new FormData(event.currentTarget);const rule:Rule={kind:"commissionRule",scope,employeeId:employee.id,employeeName:employee.displayName,product,type:String(form.get("type")) as Rule["type"],value:Number(form.get("value")||0)};void operate({action:"saveCustomerCatalog",id:existing?.entry.id,catalog:"commissionRule",name:`${scopeLabel(scope)} · ${employee.displayName} · ${product}`,catalogDescription:JSON.stringify(rule),active:true},"Regra de comissão salva.")};
  const entries=scope==="commercial"?(products.length?products.map(entry=>entry.name):["Todos os produtos"]):["*"];
  return <section className="commission-settings"><header className="module-page-header"><div className="module-page-title"><span className="module-page-title-icon"><Settings/></span><span className="module-page-copy"><span className="eyebrow">COMISSÕES · CONFIGURAÇÕES</span><h1>Regras por colaborador</h1><p>Defina percentuais ou valores fixos para cada produto e setor.</p></span></div><button className="secondary-button" onClick={onBack}>← Voltar às comissões</button></header><nav className="commission-tabs"><button className={scope==="commercial"?"active":""} onClick={()=>setScope("commercial")}>Comercial</button><button className={scope==="cs"?"active":""} onClick={()=>setScope("cs")}>Sucesso do Cliente</button><button className={scope==="lia"?"active":""} onClick={()=>setScope("lia")}>LIA</button></nav><section className="commission-rule-picker panel"><label>Colaborador<select value={employeeId} onChange={event=>setEmployeeId(event.target.value)}><option value="">Selecionar colaborador</option>{employees.map(entry=><option key={entry.id} value={entry.id}>{entry.displayName} · {entry.departmentName}</option>)}</select></label><p>{scope==="commercial"?"Configure uma regra para cada produto vendido.":`Configure o percentual fixo para a carteira de ${scopeLabel(scope)}.`}</p></section>{!employee?<div className="commission-empty"><UsersRound/><h2>Selecione um colaborador</h2><p>As regras serão abertas após a seleção.</p></div>:<section className="commission-rule-list">{entries.map(product=>{const productKey=scope==="commercial"?(product==="Todos os produtos"?"*":product):"*";const existing=rules.find(entry=>entry.rule.scope===scope&&entry.rule.employeeId===employee.id&&entry.rule.product===productKey);return <form key={`${scope}-${employee.id}-${productKey}`} onSubmit={event=>save(event,productKey,existing)}><span><strong>{scope==="commercial"?product:`Carteira de ${scopeLabel(scope)}`}</strong><small>{existing?"Regra configurada":"Sem regra"}</small></span><label>Tipo<select name="type" defaultValue={existing?.rule.type||"percentage"}><option value="percentage">Porcentagem</option>{scope==="commercial"&&<option value="fixed">Valor fixo</option>}</select></label><label>Percentual ou valor<input name="value" type="number" min="0" step="0.01" required defaultValue={existing?.rule.value||0}/></label><button className="primary-button" disabled={busy}><Save/>{existing?"Atualizar":"Salvar"}</button></form>})}</section>}</section>
}
