"use client";

import { BadgeCheck, CalendarDays, ChevronRight, Columns3, FileText, Film, ImageIcon, List, Mail, Megaphone, MessageCircle, Pencil, Plus, Save, Search, Settings, Trash2, Upload, UserCheck, X, XCircle } from "lucide-react";
import { FormEvent, useMemo, useRef, useState } from "react";
import type { AgendaModuleData } from "@/app/AgendaModule";
import ReminderAction from "@/app/ReminderAction";

type Operation=(payload:Record<string,unknown>,success:string)=>Promise<{id?:string}|false>;
type Item={id:string;module:string;record_type:string;title:string;customer_name:string;owner:string;team:string;status:string;priority:string;amount_cents:number;description:string;version:number;updated_at:string;created_at:string};
type Employee={id:string;displayName:string;departmentName:string;photoDataUrl?:string;active:boolean};
type CurrentUser={displayName:string;email:string;isCoordinator:boolean};
type Props={items:Item[];employees:Employee[];currentUser:CurrentUser;agendaModule?:AgendaModuleData|null;canEdit:boolean;busy:boolean;operate:Operation;onOpenSettings?:()=>void};
type MarketingType="Solicitação"|"Criativo"|"Vídeo"|"Conteúdo"|"E-mail marketing"|"WhatsApp";
type Attachment={id:string;name:string;type:string;dataUrl:string;uploadedAt:string;uploadedBy:string};
type Comment={id:string;text:string;at:string;by:string;kind?:"comment"|"approval"|"rejection"|"schedule"};
type Detail={kind:"marketingRequest";type:MarketingType;campaign:string;channel:string;dueDate:string;summary:string;createdAt:string;comments:Comment[];attachments:Attachment[]};

const TYPES:Array<{id:"all"|MarketingType;label:string;icon:typeof ImageIcon}>=[
  {id:"all",label:"Visão geral",icon:Megaphone},{id:"Solicitação",label:"Solicitações",icon:FileText},
  {id:"Criativo",label:"Criativos",icon:ImageIcon},{id:"Vídeo",label:"Vídeos",icon:Film},
  {id:"Conteúdo",label:"Conteúdos",icon:Pencil},{id:"E-mail marketing",label:"E-mail marketing",icon:Mail},
  {id:"WhatsApp",label:"WhatsApp",icon:MessageCircle},
];
const STAGES=["Recebida","Em planejamento","Em produção","Em revisão","Concluída"];
const marketingStage=(status:string)=>STAGES.includes(status)?status:"Recebida";
const date=(value:string)=>value?new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`)):"Sem prazo";
const dt=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
function parse(value:string,recordType:string):Detail { try { const raw=JSON.parse(value) as Partial<Detail>; const type=(raw.type||recordType) as MarketingType; return {kind:"marketingRequest",type:TYPES.some(entry=>entry.id===type)?type:"Solicitação",campaign:raw.campaign??"",channel:raw.channel??"",dueDate:raw.dueDate??"",summary:raw.summary??"",createdAt:raw.createdAt??"",comments:Array.isArray(raw.comments)?raw.comments:[],attachments:Array.isArray(raw.attachments)?raw.attachments:[]}; } catch { return {kind:"marketingRequest",type:"Solicitação",campaign:"",channel:"",dueDate:"",summary:"",createdAt:"",comments:[],attachments:[]}; } }

export default function MarketingWorkspaceModule({items,employees,currentUser,agendaModule,canEdit,busy,operate,onOpenSettings}:Props){
  const [area,setArea]=useState<"all"|MarketingType>("all"); const [query,setQuery]=useState(""); const [owner,setOwner]=useState("all"); const [view,setView]=useState<"kanban"|"list">("kanban");
  const [creating,setCreating]=useState(false); const [editing,setEditing]=useState<Item|null>(null); const [selected,setSelected]=useState<Item|null>(null); const [dragging,setDragging]=useState<Item|null>(null); const [dropStage,setDropStage]=useState("");
  const records=useMemo(()=>items.filter(item=>item.module==="marketing").map(item=>({item,detail:parse(item.description,item.record_type)})),[items]);
  const visible=records.filter(({item,detail})=>(area==="all"||detail.type===area)&&(owner==="all"||item.owner===owner)&&(!query.trim()||`${item.title} ${detail.campaign} ${detail.channel} ${detail.summary} ${item.owner}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))));
  const owners=[...new Set([...employees.filter(employee=>employee.active).map(employee=>employee.displayName),...records.map(record=>record.item.owner)].filter(Boolean))];
  const move=async(item:Item,stage:string,message=`Item movido para ${stage}.`)=>{if(!canEdit||busy||marketingStage(item.status)===stage)return false;const result=await operate({action:"transitionWorkItem",id:item.id,nextStatus:stage,version:item.version,confirmed:true,boardMove:true},message);if(result&&selected?.id===item.id)setSelected({...item,status:stage,version:item.version+1});return Boolean(result)};
  const moveDropped=async(stage:string)=>{if(dragging)await move(dragging,stage);setDragging(null);setDropStage("")};
  const saveSelected=async(detail:Detail,ownerName=selected?.owner)=>{if(!selected)return false;const result=await operate({action:"updateWorkItem",id:selected.id,title:selected.title,customerName:selected.customer_name,owner:ownerName,amountCents:selected.amount_cents,version:selected.version,description:JSON.stringify(detail)},"Solicitação de Marketing atualizada.");if(result)setSelected({...selected,owner:ownerName||selected.owner,description:JSON.stringify(detail),version:selected.version+1,updated_at:new Date().toISOString()});return Boolean(result)};
  return <section className="marketing-workspace">
    <header className="marketing-workspace-head module-page-header"><div className="module-page-title"><span className="marketing-head-icon module-page-title-icon"><Megaphone size={20}/></span><span className="module-page-copy"><p className="eyebrow">OPERAÇÃO · MARKETING</p><h1>Gestão de Marketing</h1><p>Solicitações, criativos, campanhas de e-mail e WhatsApp em um único fluxo.</p></span></div><div className="module-page-actions">{onOpenSettings&&<button className="icon-button" onClick={onOpenSettings} aria-label="Configurar Marketing"><Settings size={18}/></button>}{canEdit&&<button className="primary-button" onClick={()=>setCreating(true)}><Plus size={16}/> Novo item</button>}</div></header>
    <nav className="marketing-area-tabs" aria-label="Áreas do Marketing">{TYPES.map(entry=>{const Icon=entry.icon;const count=entry.id==="all"?records.length:records.filter(record=>record.detail.type===entry.id).length;return <button key={entry.id} className={area===entry.id?"active":""} onClick={()=>setArea(entry.id)}><Icon size={15}/><span>{entry.label}</span><b>{count}</b></button>})}</nav>
    <section className="marketing-toolbar"><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar campanha, canal ou responsável"/></label><select value={owner} onChange={event=>setOwner(event.target.value)}><option value="all">Todos os responsáveis</option>{owners.map(entry=><option key={entry}>{entry}</option>)}</select><strong>{visible.length} item(ns)</strong><div><button className={view==="kanban"?"active":""} onClick={()=>setView("kanban")}><Columns3 size={15}/></button><button className={view==="list"?"active":""} onClick={()=>setView("list")}><List size={15}/></button></div></section>
    {view==="kanban"?<div className="standard-kanban marketing-kanban">{STAGES.map(stage=><section className={`standard-kanban-column ${dropStage===stage?"drag-target":""}`} key={stage} onDragOver={event=>{if(canEdit){event.preventDefault();setDropStage(stage)}}} onDrop={event=>{event.preventDefault();void moveDropped(stage)}}><header><strong>{stage}</strong><span>{visible.filter(record=>marketingStage(record.item.status)===stage).length}</span></header>{visible.filter(record=>marketingStage(record.item.status)===stage).map(({item,detail})=><article className="standard-card marketing-card" draggable={canEdit} data-reminder-entity-id={item.id} data-reminder-customer-name={item.customer_name||item.title} onDragStart={event=>{setDragging(item);event.dataTransfer.setData("text/plain",item.id)}} onDragEnd={()=>{setDragging(null);setDropStage("")}} onClick={()=>!dragging&&setSelected(item)} key={item.id}><small>{detail.type}</small><h3>{item.title}</h3><p>{detail.campaign||detail.summary||"Sem campanha vinculada"}</p><div><span>{detail.channel||"Canal não informado"}</span><span>{date(detail.dueDate)}</span></div>{detail.attachments.length>0&&<span className="marketing-media-count"><ImageIcon size={13}/>{detail.attachments.length} arquivo(s)</span>}<footer><span className="marketing-owner-chip" data-collaborator-name={item.owner}>{item.owner||"Fila de Marketing"}</span><ChevronRight size={16}/></footer>{canEdit&&<span className="marketing-card-actions"><button onClick={event=>{event.stopPropagation();setEditing(item)}}><Pencil size={14}/></button><button className="delete" onClick={event=>{event.stopPropagation();void operate({action:"deleteWorkItem",id:item.id},"Item de Marketing excluído.")}}><Trash2 size={14}/></button></span>}</article>)}</section>)}</div>:<div className="marketing-list"><header><span>TIPO</span><span>ITEM</span><span>CAMPANHA</span><span>CANAL</span><span>RESPONSÁVEL</span><span>ETAPA</span><span>PRAZO</span><span/></header>{visible.map(({item,detail})=><button key={item.id} onClick={()=>setSelected(item)}><span>{detail.type}</span><span><strong>{item.title}</strong><small>{detail.summary}</small></span><span>{detail.campaign||"—"}</span><span>{detail.channel||"—"}</span><span>{item.owner}</span><span>{marketingStage(item.status)}</span><span>{date(detail.dueDate)}</span><ChevronRight size={15}/></button>)}</div>}
    {visible.length===0&&<div className="marketing-empty"><ImageIcon size={25}/><h2>Nenhum item encontrado</h2><p>Cadastre o primeiro item ou ajuste os filtros.</p></div>}
    {creating&&<MarketingItemModal initialType={area==="all"?"Solicitação":area} employees={employees} currentUser={currentUser.displayName} busy={busy} onClose={()=>setCreating(false)} onSave={async payload=>{const result=await operate({action:"createWorkItem",module:"marketing",recordType:payload.type,title:payload.title,owner:payload.owner,team:"Marketing",status:"Recebida",priority:"P3",amountCents:0,description:JSON.stringify(payload.detail)},`${payload.type} cadastrado no Marketing.`);if(result)setCreating(false)}}/>}
    {editing&&<MarketingItemModal item={editing} initialType={parse(editing.description,editing.record_type).type} employees={employees} currentUser={currentUser.displayName} busy={busy} onClose={()=>setEditing(null)} onSave={async payload=>{const result=await operate({action:"updateWorkItem",requireConfirmation:true,id:editing.id,title:payload.title,owner:payload.owner,customerName:editing.customer_name,amountCents:editing.amount_cents,version:editing.version,description:JSON.stringify(payload.detail)},"Item de Marketing atualizado.");if(result)setEditing(null)}}/>}
    {selected&&<MarketingDrawer item={selected} detail={parse(selected.description,selected.record_type)} employees={employees} currentUser={currentUser} agendaModule={agendaModule} canEdit={canEdit} busy={busy} operate={operate} onClose={()=>setSelected(null)} onSave={saveSelected} onStage={(stage,versionOverride)=>move(versionOverride===undefined?selected:{...selected,version:versionOverride},stage)} onDelete={async()=>{if(await operate({action:"deleteWorkItem",id:selected.id},"Item de Marketing excluído."))setSelected(null)}}/>}
  </section>;
}

function MarketingItemModal({item,initialType,employees,currentUser,busy,onClose,onSave}:{item?:Item;initialType:MarketingType;employees:Employee[];currentUser:string;busy:boolean;onClose:()=>void;onSave:(payload:{title:string;owner:string;type:MarketingType;detail:Detail})=>Promise<void>}){
  const existing=item?parse(item.description,item.record_type):null; const [type,setType]=useState<MarketingType>(existing?.type??initialType);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const detail:Detail={kind:"marketingRequest",type,campaign:String(form.get("campaign")||""),channel:String(form.get("channel")||""),dueDate:String(form.get("dueDate")||""),summary:String(form.get("summary")||""),createdAt:existing?.createdAt||new Date().toISOString(),comments:existing?.comments??[],attachments:existing?.attachments??[]};void onSave({title:String(form.get("title")||""),owner:String(form.get("owner")||currentUser),type,detail})};
  return <div className="modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><section className="modal marketing-item-modal"><header className="modal-head"><div><p className="eyebrow">GESTÃO DE MARKETING</p><h2>{item?"Editar item":"Novo item"}</h2><p>Cadastre as informações com boa leitura e contexto operacional.</p></div><button className="icon-button" onClick={onClose}><X size={20}/></button></header><form className="form-grid" onSubmit={submit}><label>Tipo *<select value={type} onChange={event=>setType(event.target.value as MarketingType)}>{TYPES.filter(entry=>entry.id!=="all").map(entry=><option key={entry.id}>{entry.id}</option>)}</select></label><label>Responsável *<select name="owner" defaultValue={item?.owner||currentUser}>{employees.filter(e=>e.active).map(e=><option key={e.id}>{e.displayName}</option>)}</select></label><label className="wide">Título *<input name="title" required autoFocus defaultValue={item?.title}/></label><label>Campanha<input name="campaign" defaultValue={existing?.campaign}/></label><label>Canal<select name="channel" defaultValue={existing?.channel}><option value="">Selecionar</option><option>Instagram</option><option>YouTube</option><option>WhatsApp</option><option>E-mail</option><option>Site</option><option>Interno</option></select></label><label>Prazo<input name="dueDate" type="date" defaultValue={existing?.dueDate}/></label><label className="wide">Resumo *<textarea name="summary" required rows={5} defaultValue={existing?.summary}/></label><div className="form-actions wide"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}><Save size={16}/>{item?"Salvar alterações":"Criar item"}</button></div></form></section></div>;
}

function MarketingDrawer({item,detail,employees,currentUser,agendaModule,canEdit,busy,operate,onClose,onSave,onStage,onDelete}:{item:Item;detail:Detail;employees:Employee[];currentUser:CurrentUser;agendaModule?:AgendaModuleData|null;canEdit:boolean;busy:boolean;operate:Operation;onClose:()=>void;onSave:(detail:Detail,owner?:string)=>Promise<boolean>;onStage:(stage:string,versionOverride?:number)=>Promise<boolean>;onDelete:()=>Promise<void>}){
  const [comment,setComment]=useState(""); const [reviewReason,setReviewReason]=useState(""); const [scheduleOpen,setScheduleOpen]=useState(false); const [preview,setPreview]=useState<Attachment|null>(null); const fileRef=useRef<HTMLInputElement>(null); const stage=marketingStage(item.status);
  const add=async(text=comment,kind:Comment["kind"]="comment")=>{if(!text.trim())return false;const saved=await onSave({...detail,comments:[...detail.comments,{id:crypto.randomUUID(),text:text.trim(),at:new Date().toISOString(),by:currentUser.displayName,kind}]});if(saved)setComment("");return saved};
  const upload=async(files:FileList|null)=>{if(!files?.length)return;const accepted=Array.from(files).filter(file=>file.type.startsWith("image/")&&file.size<=5*1024*1024);const created=await Promise.all(accepted.map(file=>new Promise<Attachment>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,type:file.type,dataUrl:String(reader.result||""),uploadedAt:new Date().toISOString(),uploadedBy:currentUser.displayName});reader.onerror=reject;reader.readAsDataURL(file)})));await onSave({...detail,attachments:[...detail.attachments,...created]});if(fileRef.current)fileRef.current.value=""};
  const assume=async()=>{if(item.owner===currentUser.displayName)return;await onSave({...detail,comments:[...detail.comments,{id:crypto.randomUUID(),text:`Tarefa assumida por ${currentUser.displayName}.`,at:new Date().toISOString(),by:currentUser.displayName,kind:"comment"}]},currentUser.displayName)};
  const decide=async(approved:boolean)=>{if(!approved&&reviewReason.trim().length<3)return;const text=approved?"Card aprovado pela coordenação e concluído.":`Card reprovado pela coordenação. Motivo: ${reviewReason.trim()}`;if(await add(text,approved?"approval":"rejection"))await onStage(approved?"Concluída":"Em produção",item.version+1)};
  return <div className="drawer-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><aside className="journey-drawer marketing-drawer" data-reminder-source-module="marketing" data-reminder-source-entity-id={item.id} data-reminder-source-title={item.title} onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">MARKETING · {detail.type.toUpperCase()}</p><h2>{item.title}</h2><span>{detail.campaign||"Sem campanha"}</span></div><div className="marketing-drawer-head-actions"><ReminderAction compact={false} context={{module:"marketing",entityId:item.id,customerName:item.customer_name||item.title,title:item.title,summary:detail.summary,recipientName:item.owner}}/><button className="icon-button" onClick={onClose}><X size={18}/></button></div></header><div className="journey-drawer-body">
    <section className="journey-summary-grid"><div><small>Responsável</small><strong>{item.owner||"Fila de Marketing"}</strong></div><div><small>Etapa</small><strong>{stage}</strong></div><div><small>Canal</small><strong>{detail.channel||"Não informado"}</strong></div><div><small>Prazo</small><strong>{date(detail.dueDate)}</strong></div></section>
    <section className="journey-action-card"><h3>Resumo</h3><p>{detail.summary}</p></section>
    {canEdit&&<section className="marketing-primary-actions"><button className="secondary-button" onClick={()=>setScheduleOpen(true)}><CalendarDays size={16}/> Agendar</button><button className="primary-button" disabled={busy||item.owner===currentUser.displayName} onClick={()=>void assume()}><UserCheck size={16}/>{item.owner===currentUser.displayName?"Tarefa assumida":"Assumir tarefa"}</button></section>}
    {canEdit&&<section className="journey-action-card"><label>Alterar etapa<select value={stage} disabled={busy} onChange={event=>void onStage(event.target.value)}>{STAGES.map(entry=><option key={entry}>{entry}</option>)}</select></label></section>}
    {stage==="Em revisão"&&currentUser.isCoordinator&&canEdit&&<section className="marketing-review-panel"><header><BadgeCheck size={19}/><div><h3>Revisão da coordenação</h3><p>Aprove para concluir ou devolva à produção com o motivo registrado.</p></div></header><textarea rows={3} value={reviewReason} onChange={event=>setReviewReason(event.target.value)} placeholder="Motivo obrigatório para reprovar"/><div><button className="danger-button" disabled={busy||reviewReason.trim().length<3} onClick={()=>void decide(false)}><XCircle size={16}/> Reprovar</button><button className="primary-button" disabled={busy} onClick={()=>void decide(true)}><BadgeCheck size={16}/> Aprovar e concluir</button></div></section>}
    <section className="marketing-assets"><header><div><h3><ImageIcon size={17}/> Imagens e criativos</h3><p>Clique em uma imagem para visualizar em tamanho maior.</p></div>{canEdit&&<><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={event=>void upload(event.target.files)}/><button className="secondary-button" onClick={()=>fileRef.current?.click()}><Upload size={15}/> Adicionar arquivos</button></>}</header>{detail.attachments.length?<div>{detail.attachments.map(file=><article key={file.id}><button onClick={()=>setPreview(file)}><img src={file.dataUrl} alt={file.name}/></button><span><strong>{file.name}</strong><small>{file.uploadedBy} · {dt(file.uploadedAt)}</small></span>{canEdit&&<button className="delete" onClick={()=>void onSave({...detail,attachments:detail.attachments.filter(entry=>entry.id!==file.id)})}><Trash2 size={15}/></button>}</article>)}</div>:<p className="empty-copy">Nenhuma imagem ou criativo anexado.</p>}</section>
    <section className="marketing-comments"><h3>Comentários e histórico</h3>{canEdit&&<div><textarea rows={3} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Adicione uma atualização para o time..."/><button className="primary-button" disabled={busy||!comment.trim()} onClick={()=>void add()}>Comentar</button></div>}<section>{detail.comments.length?detail.comments.slice().reverse().map(entry=><article className={entry.kind||"comment"} key={entry.id}><strong>{entry.by}</strong><small>{dt(entry.at)}</small><p>{entry.text}</p></article>):<p>Nenhum comentário registrado.</p>}</section></section>
  </div><footer>{canEdit&&<button className="secondary-button compact danger-action" onClick={()=>void onDelete()}><Trash2 size={15}/> Excluir</button>}</footer></aside>
  {scheduleOpen&&<MarketingScheduleModal item={item} detail={detail} agendaModule={agendaModule} employees={employees} busy={busy} operate={operate} onClose={()=>setScheduleOpen(false)} onSaved={async text=>{await add(text,"schedule");setScheduleOpen(false)}}/>}
  {preview&&<div className="image-preview-backdrop" onClick={()=>setPreview(null)}><section onClick={event=>event.stopPropagation()}><button onClick={()=>setPreview(null)}><X/></button><img src={preview.dataUrl} alt={preview.name}/><strong>{preview.name}</strong></section></div>}
  </div>;
}

function MarketingScheduleModal({item,detail,agendaModule,employees,busy,operate,onClose,onSaved}:{item:Item;detail:Detail;agendaModule?:AgendaModuleData|null;employees:Employee[];busy:boolean;operate:Operation;onClose:()=>void;onSaved:(message:string)=>Promise<void>}){
  const [dateValue,setDateValue]=useState(detail.dueDate||new Date().toLocaleDateString("en-CA")); const [time,setTime]=useState("09:00");
  const calendar=agendaModule?.calendars.find(entry=>entry.active&&/marketing/i.test(`${entry.name} ${entry.departmentName}`))??agendaModule?.calendars.find(entry=>entry.active);
  const type=agendaModule?.types.find(entry=>entry.active); const status=agendaModule?.statuses.find(entry=>entry.active); const responsible=agendaModule?.collaborators.find(entry=>entry.name===item.owner)??agendaModule?.collaborators[0];
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!calendar||!type||!status||!responsible)return;const startsAt=new Date(`${dateValue}T${time}:00`).toISOString();const result=await operate({action:"createAgendaCommitment",agendaId:calendar.id,agendaTypeId:type.id,agendaStatusId:status.id,responsibleUserId:responsible.id,title:`Marketing · ${item.title}`,description:detail.summary,startsAt,endsAt:new Date(new Date(startsAt).getTime()+3600000).toISOString(),participantUserIds:[],recurrence:"none"},"Compromisso de Marketing incluído na agenda.");if(result)await onSaved(`Compromisso agendado para ${date(dateValue)} às ${time}.`)};
  return <div className="modal-backdrop marketing-nested-modal"><form className="modal marketing-schedule-modal" onSubmit={submit}><header className="modal-head"><div><span className="eyebrow">MARKETING · AGENDA</span><h2>Agendar compromisso</h2><p>{item.title}</p></div><button type="button" className="icon-button" onClick={onClose}><X/></button></header><div className="form-grid"><label>Data *<input type="date" value={dateValue} onChange={event=>setDateValue(event.target.value)} required/></label><label>Horário *<input type="time" value={time} onChange={event=>setTime(event.target.value)} required/></label><label className="wide">Responsável<input readOnly value={employees.find(entry=>entry.displayName===item.owner)?.displayName||item.owner||"Fila de Marketing"}/></label></div>{(!calendar||!type||!status||!responsible)&&<p className="form-error">Configure uma agenda, tipo, status e responsável ativos para realizar o agendamento.</p>}<footer className="form-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy||!calendar||!type||!status||!responsible}><CalendarDays size={16}/> Agendar</button></footer></form></div>;
}
