"use client";

import { CalendarDays, ChevronRight, Columns3, FileText, Film, ImageIcon, List, Megaphone, Pencil, Plus, Save, Search, Settings, Trash2, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

type Operation=(payload:Record<string,unknown>,success:string)=>Promise<unknown>;
type Item={id:string;module:string;record_type:string;title:string;customer_name:string;owner:string;team:string;status:string;priority:string;amount_cents:number;description:string;version:number;updated_at:string;created_at:string};
type Employee={id:string;displayName:string;departmentName:string;active:boolean};
type Props={items:Item[];employees:Employee[];currentUser:string;canEdit:boolean;busy:boolean;operate:Operation;onOpenSettings:()=>void};
type MarketingType="Solicitação"|"Criativo"|"Vídeo"|"Conteúdo";
type Detail={kind:"marketingRequest";type:MarketingType;campaign:string;channel:string;dueDate:string;summary:string;createdAt:string};
const TYPES:Array<{id:"all"|MarketingType;label:string;icon:typeof ImageIcon}>=[{id:"all",label:"Visão geral",icon:Megaphone},{id:"Solicitação",label:"Solicitações",icon:FileText},{id:"Criativo",label:"Controle de criativos",icon:ImageIcon},{id:"Vídeo",label:"Vídeos",icon:Film},{id:"Conteúdo",label:"Conteúdos",icon:Pencil}];
const STAGES=["Recebida","Em planejamento","Em produção","Em revisão","Concluída"];
function parse(value:string,recordType:string):Detail { try { const raw=JSON.parse(value) as Partial<Detail>; return {kind:"marketingRequest",type:["Criativo","Vídeo","Conteúdo"].includes(raw.type||recordType)?(raw.type||recordType) as MarketingType:"Solicitação",campaign:raw.campaign??"",channel:raw.channel??"",dueDate:raw.dueDate??"",summary:raw.summary??"",createdAt:raw.createdAt??""}; } catch { return {kind:"marketingRequest",type:["Criativo","Vídeo","Conteúdo"].includes(recordType)?recordType as MarketingType:"Solicitação",campaign:"",channel:"",dueDate:"",summary:"",createdAt:""}; } }
const date=(value:string)=>value?new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`)):"Sem prazo";

export default function MarketingWorkspaceModule({items,employees,currentUser,canEdit,busy,operate,onOpenSettings}:Props){
  const [area,setArea]=useState<"all"|MarketingType>("all");const [query,setQuery]=useState("");const [owner,setOwner]=useState("all");const [view,setView]=useState<"kanban"|"list">("kanban");const [creating,setCreating]=useState(false);const [selected,setSelected]=useState<Item|null>(null);
  const records=useMemo(()=>items.filter(item=>item.module==="marketing").map(item=>({item,detail:parse(item.description,item.record_type)})),[items]);
  const visible=records.filter(({item,detail})=>(area==="all"||detail.type===area)&&(owner==="all"||item.owner===owner)&&(!query.trim()||`${item.title} ${detail.campaign} ${detail.channel} ${detail.summary} ${item.owner}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))));
  const owners=[...new Set([...employees.filter(employee=>employee.active).map(employee=>employee.displayName),...records.map(record=>record.item.owner)].filter(Boolean))];
  return <section className="marketing-workspace">
    <header className="marketing-workspace-head"><div><span className="marketing-head-icon"><Megaphone size={20}/></span><span><p className="eyebrow">OPERAÇÃO · MARKETING</p><h1>Gestão de Marketing</h1><p>Solicitações, criativos, vídeos e conteúdos em um único fluxo de produção.</p></span></div><div><button className="icon-button" onClick={onOpenSettings} aria-label="Configurar Marketing"><Settings size={18}/></button>{canEdit&&<button className="primary-button" onClick={()=>setCreating(true)}><Plus size={16}/> Novo item</button>}</div></header>
    <nav className="marketing-area-tabs" aria-label="Áreas do Marketing">{TYPES.map(entry=>{const Icon=entry.icon;const count=entry.id==="all"?records.length:records.filter(record=>record.detail.type===entry.id).length;return <button key={entry.id} className={area===entry.id?"active":""} onClick={()=>setArea(entry.id)}><Icon size={15}/><span>{entry.label}</span><b>{count}</b></button>})}</nav>
    <section className="marketing-toolbar"><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar campanha, solicitação, canal ou responsável"/></label><select value={owner} onChange={event=>setOwner(event.target.value)}><option value="all">Todos os responsáveis</option>{owners.map(entry=><option key={entry}>{entry}</option>)}</select><strong>{visible.length} item(ns)</strong><div><button className={view==="kanban"?"active":""} onClick={()=>setView("kanban")} aria-label="Visualizar Kanban"><Columns3 size={15}/></button><button className={view==="list"?"active":""} onClick={()=>setView("list")} aria-label="Visualizar lista"><List size={15}/></button></div></section>
    {view==="kanban"?<div className="standard-kanban marketing-kanban">{STAGES.map(stage=><section className="standard-kanban-column" key={stage}><header><strong>{stage}</strong><span>{visible.filter(record=>record.item.status===stage).length}</span></header>{visible.filter(record=>record.item.status===stage).map(({item,detail})=><article className="standard-card marketing-card" onClick={()=>setSelected(item)} key={item.id}><small>{detail.type}</small><h3>{item.title}</h3><p>{detail.campaign||detail.summary||"Sem campanha vinculada"}</p><div><span>{detail.channel||"Canal não informado"}</span><span>{date(detail.dueDate)}</span></div><footer><span>{item.owner||"Fila de Marketing"}</span><ChevronRight size={16}/></footer></article>)}</section>)}</div>:<div className="marketing-list"><header><span>TIPO</span><span>ITEM</span><span>CAMPANHA</span><span>CANAL</span><span>RESPONSÁVEL</span><span>ETAPA</span><span>PRAZO</span><span/></header>{visible.map(({item,detail})=><button key={item.id} onClick={()=>setSelected(item)}><span>{detail.type}</span><span><strong>{item.title}</strong><small>{detail.summary}</small></span><span>{detail.campaign||"—"}</span><span>{detail.channel||"—"}</span><span>{item.owner}</span><span>{item.status}</span><span>{date(detail.dueDate)}</span><span><ChevronRight size={15}/></span></button>)}</div>}
    {visible.length===0&&<div className="marketing-empty"><ImageIcon size={25}/><h2>Nenhum item encontrado</h2><p>Cadastre o primeiro item ou ajuste os filtros.</p></div>}
    {creating&&<MarketingItemModal initialType={area==="all"?"Solicitação":area} employees={employees.filter(employee=>employee.active)} currentUser={currentUser} busy={busy} onClose={()=>setCreating(false)} onSave={async({title,owner,type,detail})=>{const result=await operate({action:"createWorkItem",module:"marketing",recordType:type,title,owner,team:"Marketing",status:"Recebida",priority:"P3",amountCents:0,description:JSON.stringify(detail)},`${type} cadastrado no Marketing.`);if(result)setCreating(false);}}/>}
    {selected&&<MarketingDrawer item={selected} detail={parse(selected.description,selected.record_type)} canEdit={canEdit} busy={busy} onClose={()=>setSelected(null)} onStage={async next=>{const result=await operate({action:"transitionWorkItem",id:selected.id,nextStatus:next,version:selected.version,confirmed:true},"Etapa atualizada.");if(result)setSelected({...selected,status:next,version:selected.version+1});}} onDelete={async()=>{await operate({action:"deleteWorkItem",id:selected.id},"Item de Marketing excluído.");setSelected(null);}}/>}
  </section>;
}

function MarketingItemModal({initialType,employees,currentUser,busy,onClose,onSave}:{initialType:MarketingType;employees:Employee[];currentUser:string;busy:boolean;onClose:()=>void;onSave:(payload:{title:string;owner:string;type:MarketingType;detail:Detail})=>Promise<void>}){const [type,setType]=useState<MarketingType>(initialType);const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const detail:Detail={kind:"marketingRequest",type,campaign:String(form.get("campaign")||""),channel:String(form.get("channel")||""),dueDate:String(form.get("dueDate")||""),summary:String(form.get("summary")||""),createdAt:new Date().toISOString()};void onSave({title:String(form.get("title")||""),owner:String(form.get("owner")||currentUser),type,detail});};return <div className="modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><section className="modal marketing-item-modal"><header className="modal-head"><div><p className="eyebrow">GESTÃO DE MARKETING</p><h2>Novo item</h2><p>Escolha o tipo para direcionar o registro ao controle correto.</p></div><button className="icon-button" onClick={onClose}><X size={18}/></button></header><form className="form-grid" onSubmit={submit}><label>Tipo *<select value={type} onChange={event=>setType(event.target.value as MarketingType)}><option>Solicitação</option><option>Criativo</option><option>Vídeo</option><option>Conteúdo</option></select></label><label>Responsável *<select name="owner" required defaultValue={currentUser}><option>{currentUser}</option>{employees.filter(employee=>employee.displayName!==currentUser).map(employee=><option key={employee.id}>{employee.displayName}</option>)}</select></label><label className="wide">Título *<input name="title" required autoFocus/></label><label>Campanha<input name="campaign"/></label><label>Canal<select name="channel"><option value="">Selecionar</option><option>Instagram</option><option>YouTube</option><option>WhatsApp</option><option>E-mail</option><option>Site</option><option>Interno</option></select></label><label>Prazo<input name="dueDate" type="date"/></label><label className="wide">Resumo *<textarea name="summary" required rows={4}/></label><div className="form-actions wide"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}><Save size={15}/> Criar item</button></div></form></section></div>;}

function MarketingDrawer({item,detail,canEdit,busy,onClose,onStage,onDelete}:{item:Item;detail:Detail;canEdit:boolean;busy:boolean;onClose:()=>void;onStage:(stage:string)=>Promise<void>;onDelete:()=>Promise<void>}){return <div className="drawer-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><aside className="journey-drawer marketing-drawer" onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">MARKETING · {detail.type.toUpperCase()}</p><h2>{item.title}</h2><span>{detail.campaign||"Sem campanha"}</span></div><button className="icon-button" onClick={onClose}><X size={18}/></button></header><div className="journey-drawer-body"><section className="journey-summary-grid"><div><small>Responsável</small><strong>{item.owner}</strong></div><div><small>Etapa</small><strong>{item.status}</strong></div><div><small>Canal</small><strong>{detail.channel||"Não informado"}</strong></div><div><small>Prazo</small><strong>{date(detail.dueDate)}</strong></div></section><section className="journey-action-card"><h3>Resumo</h3><p>{detail.summary}</p></section>{canEdit&&<section className="journey-action-card"><label>Alterar etapa<select value={item.status} disabled={busy} onChange={event=>void onStage(event.target.value)}>{STAGES.map(stage=><option key={stage}>{stage}</option>)}</select></label></section>}</div><footer>{canEdit&&<button className="danger-button compact" onClick={()=>confirm("Excluir este item de Marketing?")&&void onDelete()}><Trash2 size={15}/> Excluir</button>}</footer></aside></div>;}
