"use client";

import { CalendarDays, ChevronRight, Columns3, FileText, Film, ImageIcon, List, Megaphone, Pencil, Plus, Save, Search, Settings, Trash2, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

type Operation=(payload:Record<string,unknown>,success:string)=>Promise<unknown>;
type Item={id:string;module:string;record_type:string;title:string;customer_name:string;owner:string;team:string;status:string;priority:string;amount_cents:number;description:string;version:number;updated_at:string;created_at:string};
type Employee={id:string;displayName:string;departmentName:string;photoDataUrl?:string;active:boolean};
type Props={items:Item[];employees:Employee[];currentUser:string;canEdit:boolean;busy:boolean;operate:Operation;onOpenSettings?:()=>void};
type MarketingType="Solicitação"|"Criativo"|"Vídeo"|"Conteúdo";
type Detail={kind:"marketingRequest";type:MarketingType;campaign:string;channel:string;dueDate:string;summary:string;createdAt:string;comments:Array<{id:string;text:string;at:string;by:string}>};
const TYPES:Array<{id:"all"|MarketingType;label:string;icon:typeof ImageIcon}>=[{id:"all",label:"Visão geral",icon:Megaphone},{id:"Solicitação",label:"Solicitações",icon:FileText},{id:"Criativo",label:"Controle de criativos",icon:ImageIcon},{id:"Vídeo",label:"Vídeos",icon:Film},{id:"Conteúdo",label:"Conteúdos",icon:Pencil}];
const STAGES=["Recebida","Em planejamento","Em produção","Em revisão","Concluída"];
const marketingStage=(status:string)=>STAGES.includes(status)?status:"Recebida";
function parse(value:string,recordType:string):Detail { try { const raw=JSON.parse(value) as Partial<Detail>; return {kind:"marketingRequest",type:["Criativo","Vídeo","Conteúdo"].includes(raw.type||recordType)?(raw.type||recordType) as MarketingType:"Solicitação",campaign:raw.campaign??"",channel:raw.channel??"",dueDate:raw.dueDate??"",summary:raw.summary??"",createdAt:raw.createdAt??"",comments:Array.isArray(raw.comments)?raw.comments:[]}; } catch { return {kind:"marketingRequest",type:["Criativo","Vídeo","Conteúdo"].includes(recordType)?recordType as MarketingType:"Solicitação",campaign:"",channel:"",dueDate:"",summary:"",createdAt:"",comments:[]}; } }
const date=(value:string)=>value?new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`)):"Sem prazo";

export default function MarketingWorkspaceModule({items,employees,currentUser,canEdit,busy,operate,onOpenSettings}:Props){
  const [area,setArea]=useState<"all"|MarketingType>("all");const [query,setQuery]=useState("");const [owner,setOwner]=useState("all");const [view,setView]=useState<"kanban"|"list">("kanban");const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<Item|null>(null);const [selected,setSelected]=useState<Item|null>(null);const [dragging,setDragging]=useState<Item|null>(null);const [dropStage,setDropStage]=useState("");
  const records=useMemo(()=>items.filter(item=>item.module==="marketing").map(item=>({item,detail:parse(item.description,item.record_type)})),[items]);
  const visible=records.filter(({item,detail})=>(area==="all"||detail.type===area)&&(owner==="all"||item.owner===owner)&&(!query.trim()||`${item.title} ${detail.campaign} ${detail.channel} ${detail.summary} ${item.owner}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))));
  const owners=[...new Set([...employees.filter(employee=>employee.active).map(employee=>employee.displayName),...records.map(record=>record.item.owner)].filter(Boolean))];
  const moveToStage=async(stage:string)=>{if(!dragging||!canEdit||busy||marketingStage(dragging.status)===stage){setDragging(null);setDropStage("");return;}const result=await operate({action:"transitionWorkItem",id:dragging.id,nextStatus:stage,version:dragging.version,confirmed:true,boardMove:true},`Item movido para ${stage}.`);if(result&&selected?.id===dragging.id)setSelected({...selected,status:stage,version:selected.version+1});setDragging(null);setDropStage("");};
  return <section className="marketing-workspace">
    <header className="marketing-workspace-head module-page-header"><div className="module-page-title"><span className="marketing-head-icon module-page-title-icon"><Megaphone size={20}/></span><span className="module-page-copy"><p className="eyebrow">OPERAÇÃO · MARKETING</p><h1>Gestão de Marketing</h1><p>Solicitações, criativos, vídeos e conteúdos em um único fluxo de produção.</p></span></div><div className="module-page-actions">{onOpenSettings && <button className="icon-button" onClick={onOpenSettings} aria-label="Configurar Marketing"><Settings size={18}/></button>}{canEdit&&<button className="primary-button" onClick={()=>setCreating(true)}><Plus size={16}/> Novo item</button>}</div></header>
    <nav className="marketing-area-tabs" aria-label="Áreas do Marketing">{TYPES.map(entry=>{const Icon=entry.icon;const count=entry.id==="all"?records.length:records.filter(record=>record.detail.type===entry.id).length;return <button key={entry.id} className={area===entry.id?"active":""} onClick={()=>setArea(entry.id)}><Icon size={15}/><span>{entry.label}</span><b>{count}</b></button>})}</nav>
    <section className="marketing-toolbar"><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar campanha, solicitação, canal ou responsável"/></label><select value={owner} onChange={event=>setOwner(event.target.value)}><option value="all">Todos os responsáveis</option>{owners.map(entry=><option key={entry}>{entry}</option>)}</select><strong>{visible.length} item(ns)</strong><div><button className={view==="kanban"?"active":""} onClick={()=>setView("kanban")} aria-label="Visualizar Kanban"><Columns3 size={15}/></button><button className={view==="list"?"active":""} onClick={()=>setView("list")} aria-label="Visualizar lista"><List size={15}/></button></div></section>
    {view==="kanban"?<div className="standard-kanban marketing-kanban">{STAGES.map(stage=><section className={`standard-kanban-column ${dropStage===stage?"drag-target":""}`} key={stage} onDragOver={event=>{if(canEdit){event.preventDefault();setDropStage(stage);}}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDropStage("");}} onDrop={event=>{event.preventDefault();void moveToStage(stage);}}><header><strong>{stage}</strong><span>{visible.filter(record=>marketingStage(record.item.status)===stage).length}</span></header>{visible.filter(record=>marketingStage(record.item.status)===stage).map(({item,detail})=><article className={`standard-card marketing-card ${dragging?.id===item.id?"dragging":""}`} draggable={canEdit} onDragStart={event=>{setDragging(item);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",item.id);}} onDragEnd={()=>{setDragging(null);setDropStage("");}} onClick={()=>{if(!dragging)setSelected(item);}} key={item.id}><small>{detail.type}</small><h3>{item.title}</h3><p>{detail.campaign||detail.summary||"Sem campanha vinculada"}</p><div><span>{detail.channel||"Canal não informado"}</span><span>{date(detail.dueDate)}</span></div><footer><span className="marketing-owner-chip" data-collaborator-name={item.owner}><i style={employees.find(employee=>employee.displayName===item.owner)?.photoDataUrl?{backgroundImage:`url("${employees.find(employee=>employee.displayName===item.owner)?.photoDataUrl}")`}:undefined}/>{item.owner||"Fila de Marketing"}</span><ChevronRight size={16}/></footer>{canEdit&&<span className="marketing-card-actions"><button type="button" aria-label="Editar item" title="Editar item" onClick={event=>{event.stopPropagation();setEditing(item)}}><Pencil size={14}/></button><button type="button" className="delete" aria-label="Excluir item" title="Excluir item" onClick={event=>{event.stopPropagation();void operate({action:"deleteWorkItem",id:item.id},"Item de Marketing excluído.")}}><Trash2 size={14}/></button></span>}</article>)}</section>)}</div>:<div className="marketing-list"><header><span>TIPO</span><span>ITEM</span><span>CAMPANHA</span><span>CANAL</span><span>RESPONSÁVEL</span><span>ETAPA</span><span>PRAZO</span><span/></header>{visible.map(({item,detail})=><button key={item.id} onClick={()=>setSelected(item)}><span>{detail.type}</span><span><strong>{item.title}</strong><small>{detail.summary}</small></span><span>{detail.campaign||"—"}</span><span>{detail.channel||"—"}</span><span data-collaborator-name={item.owner}>{item.owner}</span><span>{marketingStage(item.status)}</span><span>{date(detail.dueDate)}</span><span><ChevronRight size={15}/></span></button>)}</div>}
    {visible.length===0&&<div className="marketing-empty"><ImageIcon size={25}/><h2>Nenhum item encontrado</h2><p>Cadastre o primeiro item ou ajuste os filtros.</p></div>}
    {creating&&<MarketingItemModal initialType={area==="all"?"Solicitação":area} employees={employees.filter(employee=>employee.active)} currentUser={currentUser} busy={busy} onClose={()=>setCreating(false)} onSave={async({title,owner,type,detail})=>{const result=await operate({action:"createWorkItem",module:"marketing",recordType:type,title,owner,team:"Marketing",status:"Recebida",priority:"P3",amountCents:0,description:JSON.stringify(detail)},`${type} cadastrado no Marketing.`);if(result)setCreating(false);}}/>}
    {editing&&canEdit&&<MarketingEditModal item={editing} employees={employees.filter(employee=>employee.active)} busy={busy} onClose={()=>setEditing(null)} onSave={async(title,owner,detail)=>{const result=await operate({action:"updateWorkItem",requireConfirmation:true,id:editing.id,title,owner,customerName:editing.customer_name,amountCents:editing.amount_cents,version:editing.version,description:JSON.stringify(detail)},"Item de Marketing atualizado.");if(result)setEditing(null);}}/>}
    {selected&&<MarketingDrawer item={selected} detail={parse(selected.description,selected.record_type)} currentUser={currentUser} canEdit={canEdit} busy={busy} onClose={()=>setSelected(null)} onSave={async detail=>{const result=await operate({action:"updateWorkItem",id:selected.id,title:selected.title,customerName:selected.customer_name,owner:selected.owner,amountCents:selected.amount_cents,version:selected.version,description:JSON.stringify(detail)},"Solicitação de Marketing atualizada.");if(result)setSelected({...selected,description:JSON.stringify(detail),version:selected.version+1});}} onStage={async next=>{const result=await operate({action:"transitionWorkItem",id:selected.id,nextStatus:next,version:selected.version,confirmed:true},"Etapa atualizada.");if(result)setSelected({...selected,status:next,version:selected.version+1});}} onDelete={async()=>{await operate({action:"deleteWorkItem",id:selected.id},"Item de Marketing excluído.");setSelected(null);}}/>}
  </section>;
}

function MarketingItemModal({initialType,employees,currentUser,busy,onClose,onSave}:{initialType:MarketingType;employees:Employee[];currentUser:string;busy:boolean;onClose:()=>void;onSave:(payload:{title:string;owner:string;type:MarketingType;detail:Detail})=>Promise<void>}){const [type,setType]=useState<MarketingType>(initialType);const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const detail:Detail={kind:"marketingRequest",type,campaign:String(form.get("campaign")||""),channel:String(form.get("channel")||""),dueDate:String(form.get("dueDate")||""),summary:String(form.get("summary")||""),createdAt:new Date().toISOString(),comments:[]};void onSave({title:String(form.get("title")||""),owner:String(form.get("owner")||currentUser),type,detail});};return <div className="modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><section className="modal marketing-item-modal"><header className="modal-head"><div><p className="eyebrow">GESTÃO DE MARKETING</p><h2>Novo item</h2><p>Escolha o tipo para direcionar o registro ao controle correto.</p></div><button className="icon-button" onClick={onClose}><X size={18}/></button></header><form className="form-grid" onSubmit={submit}><label>Tipo *<select value={type} onChange={event=>setType(event.target.value as MarketingType)}><option>Solicitação</option><option>Criativo</option><option>Vídeo</option><option>Conteúdo</option></select></label><label>Responsável *<select name="owner" required defaultValue={currentUser}><option>{currentUser}</option>{employees.filter(employee=>employee.displayName!==currentUser).map(employee=><option key={employee.id}>{employee.displayName}</option>)}</select></label><label className="wide">Título *<input name="title" required autoFocus/></label><label>Campanha<input name="campaign"/></label><label>Canal<select name="channel"><option value="">Selecionar</option><option>Instagram</option><option>YouTube</option><option>WhatsApp</option><option>E-mail</option><option>Site</option><option>Interno</option></select></label><label>Prazo<input name="dueDate" type="date"/></label><label className="wide">Resumo *<textarea name="summary" required rows={4}/></label><div className="form-actions wide"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}><Save size={15}/> Criar item</button></div></form></section></div>;}

function MarketingEditModal({item,employees,busy,onClose,onSave}:{item:Item;employees:Employee[];busy:boolean;onClose:()=>void;onSave:(title:string,owner:string,detail:Detail)=>Promise<void>}){
  const detail=parse(item.description,item.record_type);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void onSave(String(form.get("title")||"").trim(),String(form.get("owner")||item.owner),{...detail,campaign:String(form.get("campaign")||""),channel:String(form.get("channel")||""),dueDate:String(form.get("dueDate")||""),summary:String(form.get("summary")||"")})};
  return <div className="modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><section className="modal marketing-item-modal"><header className="modal-head"><div><p className="eyebrow">GESTÃO DE MARKETING</p><h2>Editar item</h2><p>Atualize os dados sem perder os comentários ou a etapa.</p></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><form className="form-grid" onSubmit={submit}><label className="wide">Título *<input name="title" required autoFocus defaultValue={item.title}/></label><label>Responsável<select name="owner" defaultValue={item.owner}><option value={item.owner}>{item.owner}</option>{employees.filter(employee=>employee.displayName!==item.owner).map(employee=><option key={employee.id}>{employee.displayName}</option>)}</select></label><label>Campanha<input name="campaign" defaultValue={detail.campaign}/></label><label>Canal<input name="channel" defaultValue={detail.channel}/></label><label>Prazo<input name="dueDate" type="date" defaultValue={detail.dueDate}/></label><label className="wide">Resumo *<textarea name="summary" required rows={4} defaultValue={detail.summary}/></label><div className="form-actions wide"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}><Save size={15}/>Salvar alterações</button></div></form></section></div>;
}

function MarketingDrawer({item,detail,currentUser,canEdit,busy,onClose,onSave,onStage,onDelete}:{item:Item;detail:Detail;currentUser:string;canEdit:boolean;busy:boolean;onClose:()=>void;onSave:(detail:Detail)=>Promise<void>;onStage:(stage:string)=>Promise<void>;onDelete:()=>Promise<void>}){const [comment,setComment]=useState("");const add=async()=>{if(!comment.trim())return;await onSave({...detail,comments:[...detail.comments,{id:crypto.randomUUID(),text:comment.trim(),at:new Date().toISOString(),by:currentUser}]});setComment("")};const stage=marketingStage(item.status);return <div className="drawer-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><aside className="journey-drawer marketing-drawer" onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">MARKETING · {detail.type.toUpperCase()}</p><h2>{item.title}</h2><span>{detail.campaign||"Sem campanha"}</span></div><button className="icon-button" onClick={onClose}><X size={18}/></button></header><div className="journey-drawer-body"><section className="journey-summary-grid"><div><small>Responsável</small><strong data-collaborator-name={item.owner}>{item.owner}</strong></div><div><small>Etapa</small><strong>{stage}</strong></div><div><small>Canal</small><strong>{detail.channel||"Não informado"}</strong></div><div><small>Prazo</small><strong>{date(detail.dueDate)}</strong></div></section><section className="journey-action-card"><h3>Resumo</h3><p>{detail.summary}</p></section>{canEdit&&<section className="journey-action-card"><label>Alterar etapa<select value={stage} disabled={busy} onChange={event=>void onStage(event.target.value)}>{STAGES.map(entry=><option key={entry}>{entry}</option>)}</select></label></section>}<section className="marketing-comments"><h3>Comentários</h3>{canEdit&&<div><textarea rows={3} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Adicione uma atualização para o time..."/><button className="primary-button" disabled={busy||!comment.trim()} onClick={()=>void add()}>Comentar</button></div>}<section>{detail.comments.length?detail.comments.slice().reverse().map(entry=><article key={entry.id}><strong>{entry.by}</strong><small>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(entry.at))}</small><p>{entry.text}</p></article>):<p>Nenhum comentário registrado.</p>}</section></section></div><footer>{canEdit&&<button className="secondary-button compact danger-action" onClick={()=>void onDelete()}><Trash2 size={15}/> Excluir</button>}</footer></aside></div>;}
