"use client";

import { ExternalLink, Link2, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { FormEvent, useState } from "react";

export type PortalLinkCatalog={id:string;catalog:string;name:string;description:string;active:boolean};
type Operate=(payload:Record<string,unknown>,success:string)=>Promise<{id?:string}|false>;
const parseUrl=(value:string)=>{try{const parsed=JSON.parse(value) as {url?:string;description?:string};return{url:parsed.url||"",description:parsed.description||""}}catch{return{url:value,description:""}}};

export function PortalLinksAdmin({catalogs,busy,operate}:{catalogs:PortalLinkCatalog[];busy:boolean;operate:Operate}){
 const [editing,setEditing]=useState<PortalLinkCatalog|null|undefined>(undefined);const links=catalogs.filter(entry=>entry.catalog==="portalLink");
 const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const url=String(form.get("url")||"").trim();if(!/^https?:\/\//i.test(url))return;void operate({action:"saveCustomerCatalog",id:editing?.id,catalog:"portalLink",name:String(form.get("name")||"").trim(),catalogDescription:JSON.stringify({url,description:String(form.get("description")||"").trim()}),active:form.get("active")==="on"},editing?"Link atualizado.":"Link cadastrado.").then(result=>result&&setEditing(undefined))};
 return <section className="portal-links-admin"><header className="module-page-header"><div className="module-page-title"><span className="module-page-title-icon"><Link2/></span><span className="module-page-copy"><span className="eyebrow">ADMINISTRAÇÃO · PORTAL</span><h1>Links de direcionamento</h1><p>Cadastre os atalhos que serão exibidos como cards no Portal Dontus.</p></span></div><button className="primary-button" onClick={()=>setEditing(null)}><Plus/>Novo link</button></header><section className="portal-links-admin-list">{links.length===0?<div className="portal-links-empty"><Link2/><strong>Nenhum link cadastrado</strong><span>Adicione o primeiro atalho do portal.</span></div>:links.map(entry=>{const detail=parseUrl(entry.description);return <article key={entry.id}><span><Link2/></span><div><strong>{entry.name}</strong><small>{detail.description||detail.url}</small><a href={detail.url} target="_blank" rel="noreferrer">{detail.url}<ExternalLink/></a></div><b className={entry.active?"active":"inactive"}>{entry.active?"Ativo":"Inativo"}</b><button onClick={()=>setEditing(entry)}><Pencil/></button><button className="delete" onClick={()=>void operate({action:"deleteCustomerCatalog",id:entry.id},"Link excluído.")}><Trash2/></button></article>})}</section>{editing!==undefined&&<div className="modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&setEditing(undefined)}><section className="modal portal-link-modal"><header className="modal-head"><div><span className="eyebrow">LINK DO PORTAL</span><h2>{editing?"Editar link":"Novo link"}</h2><p>O endereço será aberto em uma nova guia.</p></div><button className="icon-button" onClick={()=>setEditing(undefined)}><X/></button></header><form className="form-grid" onSubmit={save}><label className="wide">Nome *<input name="name" required defaultValue={editing?.name}/></label><label className="wide">URL *<input name="url" type="url" required placeholder="https://" defaultValue={editing?parseUrl(editing.description).url:""}/></label><label className="wide">Descrição<input name="description" defaultValue={editing?parseUrl(editing.description).description:""}/></label><label className="checkbox-label"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/>Ativo</label><div className="form-actions wide"><button type="button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-button" disabled={busy}><Save/>Salvar</button></div></form></section></div>}</section>
}

export function PortalLinksPage({catalogs,onBack}:{catalogs:PortalLinkCatalog[];onBack:()=>void}){const links=catalogs.filter(entry=>entry.active&&entry.catalog==="portalLink");return <section className="portal-subpage portal-links-page"><header className="portal-subheader"><button onClick={onBack}>← Voltar ao Portal</button><span><Link2/></span><small>ATALHOS DONTUS</small><h1>Links de direcionamento</h1><p>Acesse rapidamente sistemas, materiais e ambientes cadastrados pela administração.</p></header><div className="portal-links-grid">{links.length===0?<div className="portal-empty-panel"><Link2/><h2>Nenhum link disponível</h2><p>Os atalhos ativos cadastrados pela administração aparecerão aqui.</p></div>:links.map(entry=>{const detail=parseUrl(entry.description);return <a href={detail.url} target="_blank" rel="noreferrer" key={entry.id}><span><Link2/></span><div><strong>{entry.name}</strong><small>{detail.description||"Abrir recurso externo"}</small></div><ExternalLink/></a>})}</div></section>}
